plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
    spec: "@yarnpkg/plugin-workspace-tools"

packageExtensions:
  webpack-dev-server@*:
    peerDependencies:
      webpack-cli: "*"

  webpack@*:
    peerDependencies:
      webpack-cli: "*"

  react-dnd@*:
    peerDependencies:
      "@react-dnd/invariant": "*"
